### ISSUE TITLE
训练不成功问题求助

### ISSUE THREAD

**Issue by lizhzh8** [lfjd05/abstract#2]
你这个程序在Epoch 1/50时出现错误：
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2560 values, but the requested shape has 122880
	 [[{{node dense_1/Reshape_2}}]]
两者shape不一致，您这边能训练成功吗？
谢谢了

**Comment by lfjd05** [comment]
抱歉刚看到，词向量来源于https://github.com/Embedding/Chinese-Word-Vectors中的300维度中文维基。shape的问题需要你根据你的训练数据调整，只要保证模型能跑起来就行

**Comment by lizhzh8** [comment]
嗯 谢谢
